# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sthitajoshi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sthitajoshi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sthitajoshi/k8s
          ports:
            - containerPort: 3000
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sthitajoshi
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
