# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sthitajoshi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sthitajoshi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: httpd
          ports:
            - containerPort: 3000
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sthitajoshi
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
